# Generated by Django 5.0.1 on 2026-08-02 05:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(verbose_name='Raw Job Description')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('required_skills', models.JSONField(default=list, verbose_name='Required Skills')),
                ('preferred_skills', models.JSONField(default=list, verbose_name='Preferred Skills')),
                ('technologies', models.JSONField(default=list, verbose_name='Technologies')),
                ('experience_required', models.CharField(blank=True, max_length=100, verbose_name='Experience Required')),
                ('education_requirements', models.JSONField(default=list, verbose_name='Education Requirements')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_semantic_match', models.FloatField(verbose_name='Overall Semantic Match Score')),
                ('skills_match_score', models.FloatField(verbose_name='Skills Match Score')),
                ('experience_match_score', models.FloatField(verbose_name='Experience Match Score')),
                ('matching_skills', models.JSONField(default=list, verbose_name='Matching Skills')),
                ('missing_skills', models.JSONField(default=list, verbose_name='Missing Skills')),
                ('skill_gaps', models.JSONField(default=dict, verbose_name='Skill Gap Analysis')),
                ('model_version', models.CharField(default='all-MiniLM-L6-v2', max_length=50, verbose_name='Model Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_analyses', to='ats_intelligence.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_analyses', to='resume.uploadedresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semantic Analysis',
                'verbose_name_plural': 'Semantic Analyses',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
        migrations.CreateModel(
            name='AdvancedAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.PositiveSmallIntegerField(verbose_name='Overall ATS Score')),
                ('jd_match_score', models.PositiveSmallIntegerField(verbose_name='Job Description Match Score')),
                ('skills_score', models.PositiveSmallIntegerField(verbose_name='Skills Score')),
                ('experience_score', models.PositiveSmallIntegerField(verbose_name='Experience Score')),
                ('projects_score', models.PositiveSmallIntegerField(verbose_name='Projects Score')),
                ('education_score', models.PositiveSmallIntegerField(verbose_name='Education Score')),
                ('grammar_score', models.PositiveSmallIntegerField(verbose_name='Grammar Score')),
                ('formatting_score', models.PositiveSmallIntegerField(verbose_name='Formatting Score')),
                ('recommendations', models.JSONField(default=list, verbose_name='Enhanced Recommendations')),
                ('missing_keywords', models.JSONField(default=list, verbose_name='Missing Keywords')),
                ('improvement_suggestions', models.JSONField(default=dict, verbose_name='Improvement Suggestions')),
                ('analysis_version', models.CharField(default='2.0', max_length=10, verbose_name='Analysis Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_analyses', to='resume.uploadedresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_analyses', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_analyses', to='ats_intelligence.jobdescription')),
                ('semantic_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_analyses', to='ats_intelligence.semanticanalysis')),
            ],
            options={
                'verbose_name': 'Advanced Analysis',
                'verbose_name_plural': 'Advanced Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
