# Generated by Django 5.0.1 on 2026-08-02 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_intelligence', '0001_initial'),
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['user', '-created_at'], name='ats_intelli_user_id_c8d92c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['resume', '-created_at'], name='ats_intelli_resume__e9642c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['job_description', '-created_at'], name='ats_intelli_job_des_e7ee0c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['overall_score'], name='ats_intelli_overall_7d2bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['analysis_version', '-created_at'], name='ats_intelli_analysi_b96a11_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedanalysis',
            index=models.Index(fields=['semantic_analysis'], name='ats_intelli_semanti_873ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['user', '-created_at'], name='ats_intelli_user_id_2d128d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['job_title'], name='ats_intelli_job_tit_20c2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['company_name'], name='ats_intelli_company_041829_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['user', '-created_at'], name='ats_intelli_user_id_305057_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['resume', '-created_at'], name='ats_intelli_resume__315e19_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['job_description', '-created_at'], name='ats_intelli_job_des_995d36_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['overall_semantic_match'], name='ats_intelli_overall_79bb29_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['skills_match_score'], name='ats_intelli_skills__1c776b_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticanalysis',
            index=models.Index(fields=['model_version'], name='ats_intelli_model_v_d42a6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('overall_score__gte', 0), ('overall_score__lte', 100)), name='advanced_overall_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('jd_match_score__gte', 0), ('jd_match_score__lte', 100)), name='advanced_jd_match_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('skills_score__gte', 0), ('skills_score__lte', 100)), name='advanced_skills_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('experience_score__gte', 0), ('experience_score__lte', 100)), name='advanced_experience_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('projects_score__gte', 0), ('projects_score__lte', 100)), name='advanced_projects_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('education_score__gte', 0), ('education_score__lte', 100)), name='advanced_education_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('grammar_score__gte', 0), ('grammar_score__lte', 100)), name='advanced_grammar_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='advancedanalysis',
            constraint=models.CheckConstraint(check=models.Q(('formatting_score__gte', 0), ('formatting_score__lte', 100)), name='advanced_formatting_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='semanticanalysis',
            constraint=models.CheckConstraint(check=models.Q(('overall_semantic_match__gte', 0.0), ('overall_semantic_match__lte', 1.0)), name='semantic_overall_match_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='semanticanalysis',
            constraint=models.CheckConstraint(check=models.Q(('skills_match_score__gte', 0.0), ('skills_match_score__lte', 1.0)), name='semantic_skills_match_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='semanticanalysis',
            constraint=models.CheckConstraint(check=models.Q(('experience_match_score__gte', 0.0), ('experience_match_score__lte', 1.0)), name='semantic_experience_match_valid_range'),
        ),
    ]
