# Generated by Django 5.0.1 on 2026-07-29 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10, verbose_name='File Type')),
                ('extracted_text', models.TextField(verbose_name='Extracted Text')),
                ('text_length', models.PositiveIntegerField(verbose_name='Text Length')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('job_title_context', models.CharField(blank=True, max_length=255, verbose_name='Job Title Context')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('processing_error', models.TextField(blank=True, verbose_name='Processing Error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Resume',
                'verbose_name_plural': 'Uploaded Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.PositiveSmallIntegerField(verbose_name='Overall ATS Score')),
                ('parseability_score', models.PositiveSmallIntegerField(verbose_name='Parseability Score')),
                ('structure_score', models.PositiveSmallIntegerField(verbose_name='Structure Score')),
                ('formatting_score', models.PositiveSmallIntegerField(verbose_name='Formatting Score')),
                ('content_quality_score', models.PositiveSmallIntegerField(verbose_name='Content Quality Score')),
                ('issues_found', models.JSONField(default=list, verbose_name='Issues Found')),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, verbose_name='AI Suggestions')),
                ('job_title_context', models.CharField(blank=True, max_length=255, verbose_name='Job Title Context')),
                ('analysis_version', models.CharField(default='1.0', max_length=10, verbose_name='Analysis Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resume.uploadedresume')),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'analysis_version')},
            },
        ),
    ]
